version: "3"
services:
  server:
    image: 'recipe:latest'
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/recipe?useSSL=false
#    networks:
#      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
#    networks:
#      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=recipe
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root