version: '3.9'
services:

  app:
    image: 'recipe:latest'
    build:
      context: .
    container_name: app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db1:33061/recipe

  db1:
    image: mysql
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=recipe
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 33061:3306

